name: 'Vault Secrets'
description: 'A Github Action that allows you to consume the v2 K/V backend of HashiCorp Vault™ as secure environment variables'
inputs:
  url:
    description: 'The URL for the vault endpoint'
    required: true
  secrets:
    description: 'A semicolon-separated list of secrets to retrieve. These will automatically be converted to environmental variable keys. See README for more details'
    required: true
  namespace:
    description: 'The Vault namespace from which to query secrets. Vault Enterprise only, unset by default'
    required: false
  path:
    description: 'The path of a non-default K/V engine'
    required: false
  kv-version:
    description: 'The version of the K/V engine to use.'
    default: '2'
    required: false
  method:
    description: 'The method to use to authenticate with Vault.'
    default: 'token'
    required: false
  token:
    description: 'The Vault Token to be used to authenticate with Vault'
    required: false
  roleId:
    description: 'The Role Id for App Role authentication'
    required: false
  secretId:
    description: 'The Secret Id for App Role authentication'
    required: false
  githubToken:
    description: 'The Github Token to be used to authenticate with Vault'
    required: false
  authPayload:
    description: 'The JSON payload to be sent to Vault when using a custom authentication method.'
    required: false
  extraHeaders:
    description: 'A string of newline separated extra headers to include on every request.'
    required: false
  exportEnv:
    description: 'Whether or not export secrets as environment variables.'
    default: 'true'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'unlock'
  color: 'gray-dark'
